* Learning
  Clojure runs on JVMs (OpenJDK/GraalVM)
  ClojureScript runs on NodeJS/Browser
- https://clojure.org/api/cheatsheet
- https://clojure.org/reference
- https://cljdoc.org/
- Advent ::https://github.com/fdlk/advent-2019
- Clojure Design Patterns :: http://mishadoff.com/blog/clojure-design-patterns/
- All things are data-driven lately in clojure.
- https://lambdaisland.com
- https://purelyfunctional.tv
- https://www.jacekschae.com

Books | https://github.com/clojurians-org/clojure-ebook-2

- Lisp 
  https://github.com/cswaroop/lisp-ebook
- Clojure Cookbook
  https://github.com/clojure-cookbook/clojure-cookbook/blob/master/pdf/drafts/intake.pdf
- Clojure programming cookbook
  https://www.packtpub.com/in/application-development/clojure-programming-cookbook
- 
Hangouts   
-  https://www.reddit.com/r/Clojure/
-  https://clojureverse.org/
Resources
- https://grison.me/2020/04/04/starting-with-clojure/
- https://github.com/rojoangel/rpn-calculator-kata-evaluate-clojure/blob/master/src/rpn/core.clj

Language Libs

Date & Time
- https://github.com/juxt/tick
* Compilers, Linters, REPL, IDEs
- Style Guide
  https://guide.clojure.style/
- nrepl | https://nrepl.org/

- deps.edn
- boot
- leiningen
- shadow-cljs
- babashka
- kondo
- Emacs/cider 
- VSCode/Calva
- Project template generators
  https://github.com/seancorfield/clj-new

* Datasciences
https://github.com/metasoarous/oz
Machine Learning
- MxNET
  https://github.com/apache/incubator-mxnet/tree/master/contrib/clojure-package
- Scicloj | https://scicloj.github.io/
  https://github.com/scicloj
* Datomic, DataScrip, DataHike, Crux
Innovative immutable database. Datum (E-A-V-Tx) as universal schema.  You can model relational, hierarchical, document, graph databases with this.
- Pull API 
  https://docs.datomic.com/on-prem/pull.html
  This has inspired pathom, walkable and others. some comparisions of this mehod with SQL `SELECT` or GraphQL are unavoidable.

The pull API takes three arguments
a database
a pattern
an entity identifier

#+begin_src clojure
;; Datomic Pull API
(pull db '[*] led-zeppelin)
(pull-many db '[*] [led-zeppelin jimi-hendrix janis-joplin])
;; pattern
[:artist/name :artist/gid]
[:artist/name :as "Band Name"]
[:track/name {:track/artists [:db/id :artist/name]}]
[:artist/name (:track/_artists :limit 10)]
[:artist/name (:track/_artists :limit nil)]
[:artist/name (:artist/endYear :default 0)] 
[:artist/name (:artist/endYear :default "N/A")] 
[*] 
["*"]
[* {:track/artists [:artist/name]}]
[:person/firstName :person/lastName {:person/friends 6}]
[:person/firstName :person/lastName {:person/friends ...}]
[{:track/artists [:penguins]}]
[:artist/name (limit :track/_artists 10)]
[{(limit :track/_artists 10) [:track/name]}]
[:artist/name (limit :track/_artists nil)]
[:artist/name (default :artist/endYear 0)] 
[:artist/name (default :artist/endYear "N/A")]

#+end_src


Transactin API
- https://docs.datomic.com/cloud/transactions/transaction-data-reference.html
Datomic as Graph database
- Datomic-as-GraphDB
 https://hashrocket.com/blog/posts/using-datomic-as-a-graph-database

DataScript DB
  https://github.com/tonsky/datascript
 Datahike DB
Yet another database inspired by datomic and datascript
- https://github.com/replikativ/datahike/blob/master/doc/schema.md

Crux DB
Yet another database inspired by datomic. It is database unbundled.  You can build CQRS with this db.
- https://nextjournal.cxom/crux/a-bitemporal-tale
* Datalog Query Language
So much craze for this query language, often touted more powerful than sql SELECT.
Datomic, Datahike, Crux all support Datalog
- http://www.learndatalogtoday.org/
- https://www.yetanalytics.com/blog/2014/11/20/datalog-at-play
* Algorithms
-Graph Algorithms implemented in clojure (Loom)
https://github.com/aysylu/loom/blob/master/README.md
-
* Web Applications & Microservices
- Ring
  https://github.com/ring-clojure
  Clojure HTTP server abstraction similar to Python WSGI, Ruby/Rack. spec. https://github.com/ring-clojure/ring/blob/master/SPEC
  Handlers :: for wrapping business logic.  Often a map of {Route-Handler} mapping is specified
  Middleware :: for fulfilling technical requirements such as authenticatin, content coercion etc.
  Adaptors ::
  Deploy apps on AWS using EBS, Heroku using HerokuCLI
  Ring & Compojure  were ideal combination to implement web apps. Compojure is now out of fashion and Reitit is replacing it.
- HTTPKit
  https://github.com/http-kit/http-kit
  event-driven, high-performance Clojure HTTP server/client wrapping NETTY
Hiccup(internal DSL), Selmer (external DSL) template engines
Hiccup is good for genrating fragments (div).  Selmer would be good to compose entire pages
- Hiccup (pure clojure based DSL)
  https://github.com/weavejester/hiccup
- Selmer (django style templating)
  https://github.com/yogthos/Selmer
- Enlive (CSS based selector approach)
  https://github.com/cgrand/enlive
- Skyscraper
  https://github.com/nathell/skyscraper
- Stencil (Mustache)
  https://github.com/davidsantiago/stencil
- Bootleg ; A standalone templating engine
  https://github.com/retrogradeorbit/bootleg
- Cryogen : A static website generator
  https://github.com/cryogen-project/cryogen
- Sablano : Hiccup style template for Facebook react
  https://github.com/r0man/sablono
  Not being used afer reagent/reframe
- Reagent wrapping React lib
  https://github.com/reagent-project/reagent
  https://purelyfunctional.tv/guide/reagent/
- Reframe wrapping reagent for providing Flux like framework for building SPAs
  https://github.com/day8/re-frame
- Reitit routing library 
  https://github.com/metosin/reitit
- Muntaja - content negotiation
  https://github.com/metosin/muuntaja
- Jsonista - as Cheshire is slow
  https://github.com/metosin/jsonista
- Buddy
  To use JWT, JWE
  https://github.com/funcool/buddy
- Domino ; Want to express business logic as DAG with data model, events and effects (like reframe?)
  https://github.com/domino-clj/domino
- Jevelin; a spreadsheet like programming model
  https://github.com/hoplon/javelin
- Falcro ; webstack for SPA
  https://github.com/fulcrologic/fulcro
- Duct ; 
  https://github.com/duct-framework/duct
- Pedestal
  http://pedestal.io/
  A nice API server to plugin application logic
- Keechma ; like reframe built on top of reagent
  https://github.com/keechma/keechma
- Posh
  https://github.com/denistakeda/posh
- Precept
  https://github.com/CoNarrative/precept
  See PrecursorApp 
- Juxt.Apex
  https://github.com/juxt/apex
  Want to implement a OpenAPI3 based microservice with authentication?
- Lacinia  ; GraphQL for Clojure
  https://github.com/walmartlabs/lacinia
- Hoplon
  https://github.com/hoplon/hoplon
- Juxt.Edge
  https://github.com/juxt/edge
- Juxt.Jinx
  https://github.com/juxt/jinx
  JSON Schema validator in cloure. refer Metosin.Malli
- JavaScript
  http://expressjs.com/
  https://loopback.io/doc
- Python
  https://www.fullstackpython.com/flask.html
  https://www.djangoproject.com/start/overview/
- PHP Laravel
  https://laravel.com/docs/7.x
- Go Webframeworks
  https://gin-gonic.com/docs/
  https://revel.github.io/
  https://www.gorillatoolkit.org/
  https://gobuffalo.io/en/
- Clojure Luminus 
  https://luminusweb.com/
  https://github.com/luminus-framework
  opinionated collection of libs for assembling webstack.
  compare with JUXT.edge
Archive:
- http://compojure.org/

** Servers
   - Immutant (Undertow) | http://immutant.org/
   - Jetty 
   - HTTPKit (jetty)  | https://github.com/http-kit/http-kit
   - Aleph (netty) | https://github.com/ztellman/aleph 
Connectors
http://clojurewerkz.org/   

* Games
- Clojure 2D
  https://github.com/Clojure2D/clojure2d
- Play CLJC
  https://github.com/oakes/play-cljc
- Snake game :: https://fn-code.blogspot.com/2015/08/a-clojure-snake-game.html
- Go 
  https://github.com/ztellman/pushkin/

* Spec related 
Typesystems for dynamic languages and need to describe schemas for data structures have a need to describe the structure and computation.
for Strucure you can use Metosin.Malli and for computation you can use Clojure.Spec
- https://clojure.org/guides/spec
- https://github.com/jeaye/orchestra
- https://github.com/gnl/ghostwheel

* Malli
  finally a schema for clojure data strucures possibly for JSON/XML too.  Modeled similar to prismatic schema only better.
  https://github.com/metosin/malli
* EDN and EQL
EDN is a superset of JSON modelled after clojure datastrucures.  Ever since clojure has become Data-Driven, EDN has gained popularity to represent everything (Query, configuration, process)
https://github.com/edn-format/edn

EQL is simple query language modelled after Datomic PULL API.  EQL queries are clojure data strucures. So easy to compose/generate.  EQL is similar to GraphQL.
https://edn-query-language.org/eql/1.0.0/what-is-eql.html

Onwire format
https://github.com/cognitect/transit-clj

* JDBC
next.jdbc
https://github.com/seancorfield/next-jdbc

SQL as EQL
- https://github.com/wilkerlucio/pathom
- https://github.com/walkable-server/walkable
- https://github.com/exoscale/seql

HoneySQL
SQL as Clojure data structures. Build queries programmatically -- even at runtime -- without having to bash strings together.
- https://github.com/jkk/honeysql
- HoneySQL-Postgres
  https://github.com/nilenso/honeysql-postgres

HugSQL
SQL in seperate sql files with some conventions to integrate them in clojure.
https://www.hugsql.org/

Connectionpool:
Hikari, c3p

Archive:
https://github.com/clojure/java.jdbc 
https://github.com/korma/Korma
* Deployment
AWS
- https://github.com/cognitect-labs/aws-api
- https://github.com/grav/aws-lumo-cljs-runtime
Dokku
- https://github.com/dokku/dokku/
Openshift
- https://docs.okd.io/latest/rest_api/index.html
Kubernetes
- https://github.com/kubernetes/kubernetes
* Component models and System development
  To support reloadable workflow
- https://github.com/tolitius/mount
- https://github.com/stuartsierra/component
- https://github.com/weavejester/integrant
  Configuration files
- https://github.com/juxt/aero  

* Rule Engine
- https://github.com/cerner/clara-rules
- https://github.com/oakes/clarax

* Stream Processing
- http://www.onyxplatform.org/
* Chatops
- https://github.com/yetibot/yetibot
* Distributed Systems Testing
https://github.com/jepsen-io/jepsen
* Network monitoring
https://github.com/riemann/riemann

* Applications
Production applications 
- Metabase  ; BI Server
  https://github.com/metabase/metabase
- Lipas 
  https://github.com/lipas-liikuntapaikat/lipas
- Vetd  ; SaaS buying plaform
  https://github.com/Vetd-Inc/vetd-app  
- Ventas  ; Ecommerce Engine
  https://github.com/JoelSanchez/ventas
- Uxbox  ; UX IDE
  https://github.com/uxbox/uxbox
- PrecursorApp ; https://precursorapp.com/
  https://github.com/PrecursorApp

* Integration
  - https://github.com/syndesisio/syndesis
* Blogs and Resources
- https://www.bradcypert.com/
- https://aphyr.com/tags/Clojure-from-the-ground-up
- https://tech.toryanderson.com/2018/06/29/extending-honeysql-with-json-operators/
- 
* Benchmarking
- Criterium
  https://github.com/hugoduncan/criterium
* GPU programming
- OpenCL
  https://github.com/uncomplicate/clojurecl
