#+TITLE:  EMACS Notes
#+AUTHOR: swaroop chalasani
#+EMAIL:  cswaroop@gmail.com
#+DATE:   <2020-04-23 Thu>
#+TAGS:   emacs notes

Emacs  is a great operating system, lacking only a decent editor!  EVIL mode
fixes it. Hence trying out spacemacs with EVIL mode. 


 - Documenation and Quick Note taking
 - Code editor
 - Better Operating Shell
 - https://emacsconf.org/
 - https://github.com/howardabrams/dot-files/
- https://github.com/practicalli/spacemacs


* Dot files
- https://www.youtube.com/watch?v=HKF41ivkBb0
  https://github.com/TheBB/spacemacs-layers/blob/master/init.el
- Howard Abrams
https://www.youtube.com/channel/UCVHICXXtKG7rZgtC5xonNdQ
https://github.com/howardabrams/dot-files

* Spacemacs
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org
** Layers
   https://gitahub.com/syl20bnr/spacemacs/tree/master/layers
* Appearances first
-  Theme :: Sanityinc tomorrow (M-x Package-refresh-contents and select)
-  Font :: Source Code Pro & Source sans pro. Download from net ( TrueType fonts)
- Key :: Map CapsLock to Ctrl with AutoHotKey on windows
* Documentation
- OrgMode  with Ox backend to export to any format including Latex, Hugo etc.
* Coding
For Reproduceable research, liteatate programming, literate devops
- Org-mode with Babel 
* Tags generation using ctags/gtags
* Snippets
  Use Alt-/ for  auto complete
* search engine
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bweb-services/search-engine

Evil	Holy	Command
SPC a /	C-c /	Summon a Helm buffer to select any engine

* ctags
scoop install ctags
* Lisp State for LISP/CLOJURE editing
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#lisp-key-bindings
* Org Babel
** Running Babashka on windows
https://lists.gnu.org/archive/html/emacs-orgmode/2010-12/msg00446.html
scoop install babashka
(setq org-babel-sh-command "cmd /k")

#+BEGIN_SRC shell  :results output org replace :exports results
ls | bb -i "(take 2 *input*)"
echo
#+END_SRC

#+RESULTS:
#+begin_src org
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\MyProjects\dotfiles>ls | bb -i "(take 2 *input*)"
("README.org" "babel")

d:\MyProjects\dotfiles>More? 
#+end_src


#+BEGIN_SRC shell  :results output org replace :exports results
bb -f babashka\pst.clj
echo
#+END_SRC

#+RESULTS:
#+begin_src org
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\MyProjects\dotfiles>bb -f babashka\pst.clj
14:31

d:\MyProjects\dotfiles>More? 
#+end_src
* Eshell
- https://www.youtube.com/watch?v=RhYNu6i_uY4
* Magit 
* Git interface for emacs
https://www.youtube.com/watch?v=vQO7F2Q9DwA
* RegExps
https://www.youtube.com/watch?v=6pqhDjQKWng
* Learn VI bindings for using EVIL mode
http://www.youtube.com/watch?v=wlR5gYd6um0

Ctrl-Z to switch between emacs and vi mode
  To toggle the hybrid style on and off use SPC t E h and M-m t E h. When off the vim style is enabled.
http://derekwyatt.org/vim/tutorials/


* TRAMP
For remote editing files over ssh
http://wikemacs.org/wiki/TRAMP
#+begin_src 
scoop install putty
#+end_src
