#+TITLE: AI Product Manager
https://d20vrrgs8k4bvw.cloudfront.net/documents/en-US/AI+Product+Manager+Nanodegree+Program+Syllabus.pdf
Need Help? Speak with an Advisor: www.udacity.com/advisor
AI Product Manager
NANODEGREE PROGRAM SYLLABUS
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 2
Overview
This ultimate goal of the AI Product Manager Nanodegree program is to help students learn the unique
skills that define the success of a machine learning product. Students will learn how to identify business
cases that can benefit from AI technologies, and implement best practices for designing datasets and
product prototypes. A graduate of this program will be able to:
• Decide to use an unsupervised, supervised, or deep learning model when approaching a
specific problem.
• Design a data annotation job to create a novel dataset.
• Build predictive models using automated machine learning tools.
• Compare the performances of learned models using suitable metrics.
• Prototype, test, and iterate on an AI product.
This program is comprised of 4 courses and 3 projects. Each project you build will be an opportunity to
demonstrate what you’ve learned in the lessons. Your completed projects will become part of a career
portfolio that will demonstrate to potential employers that you have skills in product management, design
principles, and training and evaluating machine learning models.
IN COLLABORATION WITH
Prerequisites:
No Experience
Required
Flexible Learning:
Self-paced, so
you can learn on
the schedule that
works best for you.
Estimated Time:
2 Months at
10 hours / week
Need Help?
udacity.com/advisor
Discuss this program
with an enrollment
advisor.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 3
Projects Overview
One of our main goals at Udacity is to help you create a job-ready portfolio of completed projects. Building a
project is one of the best ways to test the skills you’ve acquired and to demonstrate your newfound abilities
to future employers or colleagues. Throughout this Nanodegree program, you’ll have the opportunity to
prove your skills by building the following projects:
• Create a Medical Image Annotation Job
Design a labeled dataset that distinguishes between x-ray images that indicate health or
pneumonia in lungs; this can be used by ML engineers later on down the line to build a
diagnostic product.
• Build a Model with Google AutoML
Build a variety of different medical image classification models using Google Cloud AutoML.
You’ll have the opportunity to observe how properties of the data impact the models’ results.
• Create an AI Product Business Proposal
Put together all that you’ve learned to submit a final proposal for an AI product that considers
users, design practices, and the type of machine learning model you might use in the product.
In the sections below, you’ll find detailed descriptions of each project, along with the course material that
presents the skills required to complete the project.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 4
Course 1: Introduction to AI in Business
AI enables innovation by automating tasks that were previously repetitive, and time-consuming. Today, it seems
like every business either depends fundamentally on the capabilities of AI, or seeks to rapidly upskill its workforce
to compete in the new, AI world. Learn the foundations of AI and machine learning, starting with the unsupervised
and supervised models that are used in industry today. Understand how to develop a clear, narrow business case
for an AI application. Learn how and when to use AI in a product based on business metrics and data availability.
LEARNING OUTCOMES
LESSON ONE
Introduction to
AI and Machine
Learning
• Learn the basics of AI and machine learning, and how
 businesses derive value from AI
• Understand the meaning of key terminologies, such as
 learning, unsupervised learning, and neural networks
LESSON TWO Using AI and ML
in Business
• Learn to narrow down a business use case and decide
 when to use AI in a product
• Learn strategies for measuring the success of a product
• See how to build an AI product team that can manage data
 and test product efficacy, over time
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 5
 Course 2: Create a Dataset
Training data is the currency of AI—no model will perform successfully with poor quality input data. Learn
how to develop a relevant, complete, unique and high-quality dataset. Learn how to use Appen’s data
annotation platform to develop a labeled dataset for supervised learning. Understand how to anticipate
data failures and plan for longevity.
LEARNING OUTCOMES
LESSON ONE Data Fit &
Annotation
• Learn to analyze the size of your data and how well data fits a
 particular product use case
• Learn how to use Appen’s crowdsourced data annotation
 platform to generate a high-quality ground-truth dataset with
 human annotation
• Design annotation instructions for best-in-class results
LESSON TWO Project: Medical
Image Annotation
• Define a product goal for a medical diagnostic tool
• Design an annotation job for a medical image dataset
• Consider metrics for success, how you might improve the
 annotation design, and design test questions for annotators
Course Project
Create a Medical Image
Annotation Job
Learn how to create a novel dataset, by designing a data annotation
job. In this medical image annotation project, your goal, as a product
owner is to build a product that helps doctors quickly identify cases
of pneumonia in children. You’ll want to build a classification system
that can help flag serious cases of pneumonia and act as a diagnostic
aid for doctors. Your main task will be to create a data labeling job
using Appen’s platform, https://appen.com/solutions/platformoverview/
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 6
 Course 3: Build a Model
AI products rely upon machine learning models at their core. Understand key fundamentals of AI
models including how neural networks produce decisions and how “training” works. Understand how
training data affect the performance of a model, and how to evaluate models’ results. Learn how
transfer learning and neural architecture search make AI available to a wide variety of users.
LEARNING OUTCOMES
LESSON ONE
Training and
Evaluating a
Model
• Learn how a neural network learns from training data.
• Use test data to evaluate a trained model according to
 metrics like accuracy, precision, and recall.
• Learn how to use pre-trained models to transfer learning
 from one resource to another.
LESSON TWO Project: Build
a Model
• Build and train a model using Google’s AutoML.
• Evaluate several models and decide on the best model for a
 given product use case.
Course Project
Build a Model with
Google AutoML
In this project, get experience building models using automated
ML, from data to results (no coding required). Build your own
model using Google AutoML for a medical imaging use case. Then,
implement the model with four different variants of the data in order
to appreciate how the data affect the performance of the model.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 7
 Course 4: Measuring Impact and Updating Models
AI models are only as valuable as their impact on your business. Learn how to measure post-deployment
impact, and how to make data-informed improvements with A/B testing and versioning. Ensure that your
model continuously improves via active learning. Understand how to avoid major failures due to unwanted
bias, and how to ensure data security and compliance in different geographies. When you finally have productmarket fit, learn to plan for the future and scale your product.
LEARNING OUTCOMES
LESSON ONE
Measuring Business
Impact &
Mitigating Bias
• Learn how to measure the business outcomes of a
 launched product.
• Discuss A/B testing and versioning.
• Learn strategies for mitigating unwanted bias in a machine
 learning model and product.
• See how to scale a product, according to user audience and
 demand.
LESSON TWO Case Study:
Video Annotation
• See an end-to-end AI product development cycle.
• Learn strategies for ideating solutions to problems, and
 improving a prototype, incrementally.
• Spend your time focused on prototyping a product, and
 learn strategies for continuously learning and updating a
 machine learning model.
LESSON THREE Project: Capstone
Proposal • Develop a business proposal for an AI product.
Course Project
Capstone Proposal
In the capstone project, you will develop a business proposal
for an AI product for a use case of your choosing. You’ll develop
a business case for the product, define success metrics, scope
the dataset, plan the model development, and build a postdeployment monitoring plan. Reviewers will evaluate your
proposal for rigor and completeness.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 8
Our Classroom Experience
REAL-WORLD PROJECTS
Build your skills through industry-relevant projects. Get
personalized feedback from our network of 900+ project
reviewers. Our simple interface makes it easy to submit
your projects as often as you need and receive unlimited
feedback on your work.
KNOWLEDGE
Find answers to your questions with Knowledge, our
proprietary wiki. Search questions asked by other students
and discover in real-time how to solve the challenges that
you encounter.
STUDENT HUB
Leverage the power of community through a simple, yet
powerful chat interface built within the classroom. Use
Student Hub to connect with your technical mentor and
fellow students in your Nanodegree program.
WORKSPACES
See your code in action. Check the output and quality of
your code by running them on workspaces that are a part
of our classroom.
QUIZZES
Check your understanding of concepts learned in the
program by answering simple and auto-graded quizzes.
Easily go back to the lessons to brush up on concepts
anytime you get an answer wrong.
CUSTOM STUDY PLANS
Work with a mentor to create a custom study plan to suit
your personal needs. Use this plan to keep track of your
progress toward your goal.
PROGRESS TRACKER
Stay on track to complete your Nanodegree program with
useful milestone reminders.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 9
Learn with the Best
Alyssa SimpsonRochwerger
VP OF AI AND DATA AT APPEN
Alyssa is a customer-driven product
leader with proven experience in
scaling products from conception to
large-scale ROI. As Director of Product Management at IBM Watson, she
oversaw the development of a large
portfolio of AI products.
Kirsten Gokay
PRODUCT MANAGER AT
APPEN
Kirsten received her Bachelor’s degree
in Linguistics from UC Davis. With a
background in Customer Success, she’s
passionate about solving complex
problems with easy-to-use products.
Kiran Vajapey
SENIOR HCI DEVELOPER AT
APPEN
Kiran is a HCI Developer working on
creating new products and interfaces
to advance AI in industry. Kiran has a
Master’s in CS from Cornell and has
previous experience in HR Tech, Fintech,
and product architecture.
Meeta Dash
VP OF PRODUC T AT
APPEN
Meeta Dash is VP of Product at Appen,
which builds AI products to help
enterprises solve real world use cases. An
NIT India BTech and UC Davis MBA, she’s
built AI and Voice/Video products at Cisco,
Tokbox and CA.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 10
Learn with the Best
Andrea Butkovic
PRODUCT MANAGER AT APPEN
Andrea Butkovic is a product manager
focused on creating machine learning
powered annotation tools for AI teams
at Appen. Andrea has a degree in Geography from UC Berkeley with a focus
in Cartography.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 11
All Our Nanodegree Programs Include:
EXPERIENCED PROJECT REVIEWERS
REVIEWER SERVICES
• Personalized feedback & line by line code reviews
• 1600+ Reviewers with a 4.85/5 average rating
• 3 hour average project review turnaround time
• Unlimited submissions and feedback loops
• Practical tips and industry best practices
• Additional suggested resources to improve
TECHNICAL MENTOR SUPPORT
MENTORSHIP SERVICES
• Questions answered quickly by our team of
 technical mentors
• 1000+ Mentors with a 4.7/5 average rating
• Support for all your technical questions
PERSONAL CAREER SERVICES
CAREER COACHING
• Personal assistance in your job search
• Monthly 1-on-1 calls
• Personalized feedback and career guidance
• Access to Udacity Talent Program used by our
network of employers to source candidates
• Advice on negotiating job offers
• Interview preparation
• Resume services
• Github portfolio review
• LinkedIn profile optimization
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 12
Frequently Asked Questions
PROGRAM OVERVIEW
WHY SHOULD I ENROLL?
AI is changing the world around us at an astounding pace. For many,
Artificial Intelligence remains a mystery, and how to leverage this technology
is not always clear. This program is designed for students who want to
take advantage of AI, but don’t want or need to learn the full technical
implementation of neural networks and machine learning models. You’ll
learn how to leverage AI in the business world, from scoping datasets, testing
machine learning models, and crafting a proposal for a new product powered
by AI. Along the way you’ll build fluency in AI concepts.
WHAT JOBS WILL THIS PROGRAM PREPARE ME FOR?
This program is designed to upskill practicing product managers to build AIpowered products and bring value to their business using AI.
HOW DO I KNOW IF THIS PROGRAM IS RIGHT FOR ME?
This program is intended for anyone who wants to gain fluency and
understanding of AI use cases. If you want to learn how to leverage AI,
including how to build a dataset and how to evaluate different machine
learning models without needing to code, this program is for you.
ENROLLMENT AND ADMISSION
DO I NEED TO APPLY? WHAT ARE THE ADMISSION CRITERIA?
There is no application. This Nanodegree program accepts everyone,
regardless of experience and specific background.
WHAT ARE THE PREREQUISITES FOR ENROLLMENT?
There are no technical prerequisites. This course is intended for professionals
who have some familiarity with product management and basic data analysis.
IF I DO NOT MEET THE REQUIREMENTS TO ENROLL, WHAT SHOULD I DO?
If you need to review basic data analytics skills, we recommend the Intro to
Descriptive Statistics course.
Need Help? Speak with an Advisor: www.udacity.com/advisor AI Product Manager | 13
Frequently Asked Questions Continued
TUITION AND TERM OF PROGRAM
HOW IS THIS NANODEGREE PROGRAM STRUCTURED?
The AI Product Manager Nanodegree program is comprised of content and
curriculum to support 3 (three) projects. We estimate that students can
complete the program in two (2) months, working 10 hours per week.
Each project will be reviewed by the Udacity reviewer network. Feedback will
be provided and if you do not pass the project, you will be asked to resubmit
the project until it passes.
HOW LONG IS THIS NANODEGREE PROGRAM?
Access to this Nanodegree program runs for the length of time specified in
the payment card on the Nanodegree program overview page. If you do not
graduate within that time period, you will continue learning with month to
month payments. See the Terms of Use for other policies around the terms of
access to our Nanodegree programs.
CAN I SWITCH MY START DATE? CAN I GET A REFUND?
Please see the Udacity Nanodegree program FAQs for policies on enrollment
in our programs.
SOFTWARE AND HARDWARE
WHAT SOFTWARE AND VERSIONS WILL I NEED IN THIS PROGRAM?
There are no specific hardware or software requirements for this program,
other than access to the internet and a 64-bit computer.
