https://fico.udemy.com/course/neuroplasticity/learn/lecture/6266792#overview

How to rewire your brain
* Enriched environments

- Physical/Sensory environment
- Social Environment
- Cognitive Environment

Our Brain awakens in the NEW and works in urgency of NOW

Have you felt I just can't like with this brain anymore?  You can rewire it with new habits.  You can wash your past memory with new implanted memories. Your new brain (imagine it as a tree) can grow new branches and leaves (new nurons, dendrites, synapses etc).  As time goes the tree still grows and strengthened everyday). Repeat the new actions that lead to dream life.

Dream life? Comfort zone to be crumbled.  Life is meant to be lived fullest every single minute.



* Procrastination
When temptation is overwhelming you tend to procrastinate

** PERSON
   - Conscious (tip of iceberg)
   - Unconscious 

** unconscious  Drivers
- genetics
- life experiences
- context (surroundings)
** types
- Avoiders
  - Stress
- Freezers (flee or fight OR FREEZE)
- Non-motivated
- Rebels
  - Harsh parenting
- Low self esteem
- Perfectionists
- Thrill seekers (crave for dophomine)
  - procrastinate till the end to get thrill of finishing overnight
- Equalizers
  - everything is important and urgent.
- Addicts
  - workoholics
  - shopoholics
  
** How to stop procrastination

1 of 5 is a chronic procrastinator. Marshmallow experiment.  delayed gratification is success factor

Low will power people?  NO .  Temptation is overwhelming

People who wants less gets more!!! 

Willpower is actually hurting and leading to lower life span!!

** strategies to beat procrastination
   Motivation is better than willpower.

** Dophomine driven strategies   

   visualize enjoying doing that thing you hate doing
   visualize the satisfaction
   
   Video games are best at leveraging this dophomine shots release

   Build todo list and every finish enjoy

   mix that work with some thing pleasant. (music)

   Always look at the bright side of life

** contextual strategies

   embrace Social nature

   exectution is team work
   
   do teamup with friends to exectute

   Buddy system - who can give pep talk when hard time and celebrate 

   you are avergage of 5 people you hang out. Surround with action takers 

   temptation - get rid of it.  make it hard for you to get tempted.

   Bore yourself so much that you are ok to do what don't like

   change environment.  places in home, office etc. coffee shop?

** Brain hacks   

   - Covert start
     Just start small. Write first line
   - Wording
     I am doing it right Now. rather I should do sth
   - Third Person (personify procrastinate)
     Give a name to that procrastinate entity (dude)
** Conclusion
   https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers

   Do you have compelling vision

   Your holy grail. Your promised land.  What is that will rock yourself

   what do smell. what do you surround with.  visualize

   Print that compelling vision.  Hang it  in bedroom/bathroom/office

   
* How to change memory

How to corrupt your memory (false memory). Imaginary exercise improves the fingers
just thinking about exercise makes you stronger

fool your mind and mind will fool your body

** How to change memory
   cant change your past. can rewrite history.

https://www.psychologytoday.com/us/blog/fulfillment-any-age/201809/you-cant-change-the-past-you-can-rewrite-your-history?utm_source=FacebookPost&utm_medium=FBPost&utm_campaign=FBPost


   
   sit and reimagine your rebirth. give importance to your feelings.
   
   implanted memory substituted with a bad memory

   Re-framing 
   -----------

   look at different perspective.  

   Don't look at yourself as victim.

   No intrinsic motivation in the situation. 

   How To Reframe A Memory

1. No Intrinsic Value
2. Why am I hurt?
3. Turn it into a question
4. Evidence of the contrary
5. A new perspective
6. Formulate a new framework


Don't be bitter with bad decisions.  Without those bad decisions your risk wouldn't have payed off

| Growth mind set | Fixed mind set |
|-----------------+----------------|
|                 |                |

fixed mindset on some issues/contexts and growth mindset 

Our mind has two operating systems
1. fixed (sys-1)
2. Growth (sys-2)

Observe the bad decision
negative consequences
negative consequences of good decision
positive consequences of real scenario



* raising kids
High IQ doesn't mean they can have good relations etc.

let them do mistakes.  infact force them to do mistakes.
Let them fail infront of you.  
Don't give the answer.  
Let them sleep.
You need to give compliments.  Compliment hard work rather than smart/beautiful.  No praise. Wordsmith it .

** the attachment theory
   relatinoship with parents shapes the world view later.
   - securely attached
   - avoidenlty attached children
   - ambivalently attached children

Nothing is written in stone.  they should make secure bonds in the society.
** Kids brain
***  reptilion brain active. 
   crying means so many things.
*** Paliolimbic 
    hugging releases oxytocin
*** 
https://www.ted.com/talks/sarah_jayne_blakemore_the_mysterious_workings_of_the_adolescent_brain#t-838888
*** Childhood
*** Adolscence
**** Dophamine - thrill, quick learning, 
**** Oxytocin - bonding, hostility
*** Adult
**** Dophomine - Risk, Teaming
**** Oxytocin - 
   
* Eating Healthy


     
     






   

   
   

   
   
   



   
   

     

   


   

   









