#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: PITCH DECK
#+subtitle: A Basic Template to help you chart your startup
#+date: <2019-08-07 Wed>
#+author:
#+REVEAL_ROOT: file:///c:/reveal.js-3.8.0
#+email: cswaroop@PC
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 25.3.1 (Org mode 9.2.5)

* What is Pitch Deck?
A short overview of your business idea often used in presenting to investors and raising funds

* A Basic template
The following elements usually constitute a normal pitch deck

* Problem
What is the problem you are trying to solve?
Validate the problem with real life examples
* Solution
What is your solution to the problem?

* Unique Selling Proposition
What characteristics make your solution a "never-before" solution

* Competition and Barrier to entry
How do the current solutions compare with your solution?
How easy is it to replicate your solution?
What category of competitors do you belong to?
* Revenue Model
How do you make money off your solution?
Ex.
- Subscription Model
- Direct Sales
- Ad-based

3-5 year projects
Your top cash burn reasons?
* Target Market
- Size of the market vs the percentage you are targeting
- A granular profiling of your customer
  - Age, geography, purchase habits, personal traits
What channels will you use to get to this market?
* Product/Service
How does your product/service adds value
Try and explain in layman terms
Ideally, anyone reading this slide should understand it
* Milestones
Milestones you have reached so far.
e.g. prototypes, patents, pilots etc.
Milestones for next 1,3 and 5 years if possible
Milestones for what you would do if you got funded
* Funding so far
Mention funds raised through other investor and soft commitments
It helps credibility and validation
Mention realistic numbers for expected funding
* Team
Introduce your fouding members along with credentials, you can mention why they're involved
Exhibit unity in thinking, in strategy
* Notes
- Validate every possible slide with data.  Numbers don't lie.
- It is usually not a great idea because you think so, but because your target market said so.
- Don't be afraid to recognize that it won't work and change direction or drop it completely.  The right mdea  idea may be the next one.
- Getting funded does not mean success!
- Pitch less like a presentation and more like story!
- As long as there is fire in your heart, you will find a way.
- Patience, Perseverance and Passion



